disabled_rules: []
opt_in_rules:
  - closure_spacing
  - explicit_init
  - implicit_return
  - closure_end_indentation
  - conditional_returns_on_newline
  - empty_collection_literal
  - explicit_top_level_acl
  - operator_usage_whitespace
  - yoda_condition
  - redundant_optional_initialization
  - unused_declaration
  - unused_import
line_length:
  warning: 120
  error: 121
type_name:
  min_length: 3
  max_length: 40
  severity: error
identifier_name:
  min_length: 2
  max_length: 40
  severity: error
included:
  - Sources
  - Tests
analyzer_rules:
  - unused_import
  - unused_declaration
force_try:
  severity: error
