run:
  timeout: 5m
issues:
  exclude-use-default: false
linters-settings:
  revive:
    confidence: 0.95
    severity: error
  errcheck:
    check-type-assertions: true
    check-blank: true
linters:
  enable:
    - govet
    - revive
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - unused
    - gocyclo
    - gofumpt
  disable-all: false
gocyclo:
  min-complexity: 10
